# Generated by Django 4.1 on 2022-08-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=255, verbose_name='Login')),
                ('password', models.CharField(max_length=250, verbose_name='Password')),
                ('create_account_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
