# Generated by Django 4.1 on 2022-08-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reset_password_with_mail', '0002_code_alter_users_options_alter_users_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='email',
            new_name='mail',
        ),
    ]
